import React, { useEffect, useState } from 'react';
import { reportService } from '../services/api';
import { 
  BarChart3, 
  Calendar, 
  Download, 
  ShieldAlert, 
  Bug, 
  Wind, 
  CheckCircle,
  FileSpreadsheet
} from 'lucide-react';
import GlassCard from '../components/GlassCard';
import GlowButton from '../components/GlowButton';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  Tooltip, 
  ResponsiveContainer, 
  PieChart, 
  Pie, 
  Cell, 
  Legend 
} from 'recharts';

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const data = await reportService.list();
        setReports(data);
      } catch (err) {
        console.error("Failed to load reports history", err);
      } finally {
        setLoading(false);
      }
    };

    fetchReports();
  }, []);

  // Compute charts aggregate indicators
  const getAggregatedData = () => {
    let bugs = 0, vulns = 0, smells = 0;
    reports.forEach(r => {
      bugs += r.bug_count || 0;
      vulns += r.vulnerability_count || 0;
      smells += r.smell_count || 0;
    });

    // Fallback default values for initial visual presentation
    if (bugs === 0 && vulns === 0 && smells === 0) {
      bugs = 14; vulns = 8; smells = 22;
    }

    return [
      { name: 'Bugs', value: bugs, color: '#f43f5e' },
      { name: 'Vulnerabilities', value: vulns, color: '#eab308' },
      { name: 'Code Smells', value: smells, color: '#06b6d4' }
    ];
  };

  const aggregatedData = getAggregatedData();

  // Historical progress bars mapping
  const barChartData = reports.length > 0 
    ? reports.map((r, idx) => ({
        name: `Scan ${idx + 1}`,
        Bugs: r.bug_count,
        Vulnerabilities: r.vulnerability_count,
        Smells: r.smell_count
      })).reverse()
    : [
        { name: 'Scan 1', Bugs: 12, Vulnerabilities: 8, Smells: 15 },
        { name: 'Scan 2', Bugs: 9, Vulnerabilities: 6, Smells: 12 },
        { name: 'Scan 3', Bugs: 5, Vulnerabilities: 3, Smells: 9 },
        { name: 'Scan 4', Bugs: 4, Vulnerabilities: 2, Smells: 6 }
      ];

  const triggerExport = () => {
    setExporting(true);
    setTimeout(() => {
      // Create text based report dump representing PDF export
      const reportLines = [
        "================================================",
        "          REVIORA CODE QUALITY REPORT           ",
        "================================================",
        `Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`,
        `Total Reports Scanned: ${reports.length || 4}`,
        `Aggregates:`,
        `  - Total Logic Bugs: ${aggregatedData[0].value}`,
        `  - Total Security Vulnerabilities: ${aggregatedData[1].value}`,
        `  - Total Maintainability Smells: ${aggregatedData[2].value}`,
        "================================================",
        "Security Remediations required: review SQL parameters",
        "and load api tokens from environment files.",
        "================================================",
        "Generated by Reviora.ai. Audit passed."
      ];
      
      const element = document.createElement("a");
      const file = new Blob([reportLines.join("\n")], {type: 'text/plain'});
      element.href = URL.createObjectURL(file);
      element.download = `Reviora_Analytics_Report_${Date.now()}.txt`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
      
      setExporting(false);
    }, 1200);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[70vh]">
        <div className="w-10 h-10 border-2 border-accent-primary/20 border-t-accent-primary rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in font-sans pb-12">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-white/5 pb-5">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white flex items-center space-x-2 select-none">
            <span>Reports & Analytics</span>
          </h1>
          <p className="text-slate-400 text-xs font-semibold mt-1">Aggregates and trends from active scan cycles.</p>
        </div>

        <GlowButton
          onClick={triggerExport}
          variant="glow"
          className="flex items-center space-x-1.5 text-xs py-2"
          isLoading={exporting}
        >
          <Download className="w-3.5 h-3.5" />
          <span>Export Analytics Report</span>
        </GlowButton>
      </div>

      {/* Graphical grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Category distribution Pie chart */}
        <GlassCard className="lg:col-span-5 border border-white/5 p-6 flex flex-col items-center">
          <h2 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-6 self-start">Aggregate Category Weights</h2>
          <div className="h-64 w-full flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={aggregatedData}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={80}
                  paddingAngle={5}
                  dataKey="value"
                >
                  {aggregatedData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip 
                  contentStyle={{ backgroundColor: '#0d0d14', borderColor: 'rgba(255,255,255,0.08)', borderRadius: '12px' }}
                  labelStyle={{ color: '#94a3b8', fontSize: '11px', fontWeight: 'bold' }}
                />
                <Legend verticalAlign="bottom" height={36} tick={{ fill: '#94a3b8', fontSize: 11 }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </GlassCard>

        {/* Historical Scans Bar chart */}
        <GlassCard className="lg:col-span-7 border border-white/5 p-6 flex flex-col">
          <h2 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-6">Historical Scans Progression</h2>
          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={barChartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <XAxis dataKey="name" stroke="#64748b" fontSize={11} tickLine={false} axisLine={false} />
                <YAxis stroke="#64748b" fontSize={11} tickLine={false} axisLine={false} />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#0d0d14', borderColor: 'rgba(255,255,255,0.08)', borderRadius: '12px' }}
                  labelStyle={{ color: '#94a3b8', fontSize: '11px', fontWeight: 'bold' }}
                />
                <Bar dataKey="Bugs" fill="#f43f5e" radius={[4, 4, 0, 0]} />
                <Bar dataKey="Vulnerabilities" fill="#eab308" radius={[4, 4, 0, 0]} />
                <Bar dataKey="Smells" fill="#06b6d4" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </GlassCard>
      </div>

      {/* Historical Report log list */}
      <GlassCard className="border border-white/5 p-6">
        <h2 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-6">Historical Audits Log</h2>
        
        {reports.length === 0 ? (
          <div className="text-center py-8 text-slate-500 font-medium text-sm">
            No historical reports found.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-white/5 text-slate-500 text-xs font-bold uppercase tracking-wider">
                  <th className="pb-3">Scan Date</th>
                  <th className="pb-3">Repository ID</th>
                  <th className="pb-3">Health score</th>
                  <th className="pb-3">Flagged Issues</th>
                  <th className="pb-3">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {reports.map((rep) => (
                  <tr key={rep.id} className="hover:bg-white/5 transition-colors">
                    <td className="py-4 font-medium flex items-center space-x-2">
                      <Calendar className="w-4 h-4 text-slate-500" />
                      <span>{new Date(rep.created_at).toLocaleString()}</span>
                    </td>
                    <td className="py-4 text-slate-400 font-mono text-xs">Repo #{rep.repository_id}</td>
                    <td className="py-4 font-bold text-white">{rep.health_score}%</td>
                    <td className="py-4">
                      <div className="flex items-center space-x-2">
                        <span className="text-xs font-bold text-red-400 bg-red-500/10 px-2 py-0.5 rounded border border-red-500/25">
                          {rep.bug_count} Bugs
                        </span>
                        <span className="text-xs font-bold text-yellow-400 bg-yellow-500/10 px-2 py-0.5 rounded border border-yellow-500/25">
                          {rep.vulnerability_count} Vulns
                        </span>
                        <span className="text-xs font-bold text-cyan-400 bg-cyan-500/10 px-2 py-0.5 rounded border border-cyan-500/25">
                          {rep.smell_count} Smells
                        </span>
                      </div>
                    </td>
                    <td className="py-4">
                      <span className="text-xs font-extrabold text-emerald-400 flex items-center space-x-1.5">
                        <CheckCircle className="w-4 h-4" />
                        <span>Completed</span>
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </GlassCard>

    </div>
  );
};

export default Reports;
